apiVersion: v1
kind: Secret
metadata:
  name: pathavana-secrets
  labels:
    app: pathavana
type: Opaque
stringData:
  # Database credentials
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  DATABASE_URL: "postgresql+asyncpg://postgres:CHANGE_ME_IN_PRODUCTION@postgres:5432/pathavana"
  
  # Redis password
  REDIS_PASSWORD: ""
  REDIS_URL: "redis://redis:6379"
  
  # Application secrets
  SECRET_KEY: "CHANGE_ME_IN_PRODUCTION_GENERATE_WITH_OPENSSL_RAND_HEX_32"
  
  # External API keys
  OPENAI_API_KEY: "sk-CHANGE_ME"
  AZURE_OPENAI_API_KEY: "CHANGE_ME"
  AZURE_OPENAI_ENDPOINT: "https://your-resource.openai.azure.com/"
  AZURE_OPENAI_DEPLOYMENT_NAME: "gpt-4"
  ANTHROPIC_API_KEY: "sk-ant-CHANGE_ME"
  AMADEUS_API_KEY: "CHANGE_ME"
  AMADEUS_API_SECRET: "CHANGE_ME"
  GOOGLE_MAPS_API_KEY: "CHANGE_ME"
  
  # OAuth credentials
  GOOGLE_CLIENT_ID: "CHANGE_ME"
  GOOGLE_CLIENT_SECRET: "CHANGE_ME"
  FACEBOOK_APP_ID: "CHANGE_ME"
  FACEBOOK_APP_SECRET: "CHANGE_ME"
  MICROSOFT_CLIENT_ID: "CHANGE_ME"
  MICROSOFT_CLIENT_SECRET: "CHANGE_ME"
  
  # Email configuration
  SMTP_HOST: "smtp.gmail.com"
  SMTP_USERNAME: "CHANGE_ME"
  SMTP_PASSWORD: "CHANGE_ME"
  
  # Monitoring secrets
  GRAFANA_ADMIN_PASSWORD: "CHANGE_ME"
  GRAFANA_SECRET_KEY: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  labels:
    app: pathavana
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: # Base64 encoded Docker registry credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  labels:
    app: pathavana
type: kubernetes.io/tls
data:
  tls.crt: # Base64 encoded TLS certificate
  tls.key: # Base64 encoded TLS private key